apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::729091242513:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1IK1FONKT4W2L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::729091242513:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-16T17:09:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "96391"
  uid: eb5fd995-d18d-49a1-b0a7-7b88ef5febdd
